"""add phone number col

Revision ID: d0ef593f3864
Revises: 0c0e3be78b0f
Create Date: 2021-11-26 09:53:35.514639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ef593f3864'
down_revision = '0c0e3be78b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
